In [6]:
import pandas as pd

print("\n==============================")
print("ETAPA 1 - EXTRAÇÃO")
print("==============================")

# Interoperabilidade Técnica:
# Estamos lendo arquivos CSV de sistemas diferentes.

vendas = pd.read_csv("vendas.csv")
produtos = pd.read_csv("produtos.csv")

display(vendas)

display(produtos)

==============================
ETAPA 1 - EXTRAÇÃO
==============================

     sku  qtd
0   P044   15
1   P010   20
2   P074    9
3   P076   12
4   P001   10
..   ...  ...
95  P004    3
96  P045   12
97  P034   14
98  P072    1
99  P003    9

[100 rows x 2 columns]

     sku         nome  preco
0   P001       Webcam    795
1   P002     Mousepad    549
2   P003        Mouse   2226
3   P004      Teclado   2414
4   P005     Mousepad   2267
..   ...          ...    ...
95  P096           HD   1220
96  P097       Webcam    524
97  P098      Headset    205
98  P099        Mouse   1498
99  P100  Memória RAM   2053

[100 rows x 3 columns]